spring.application.name=task
spring.datasource.url=jdbc:postgresql://localhost:5432/task_management
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret.key=lqihtinsoybmipwmvyzeolgnldhthtozgewpfdcjbmmzktfevihkazmgciewguyt


spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

spring.datasource.hikari.auto-commit=false
server.port=8081
spring.servlet.multipart.max-file-size=20MB
spring.servlet.multipart.max-request-size=50MB
server.tomcat.max-swallow-size=50MB
server.error.include-message=always
server.error.include-stacktrace=never
server.error.include-binding-errors=never
server.error.include-exception=false

logging.level.org.springframework.web.socket=DEBUG
logging.level.org.springframework.messaging=DEBUG
